version: "3.9"

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: rbt-playwright-suites
    shm_size: "1gb"

  tests-full:
    image: rbt-playwright-suites
    environment:
      CI: "1"
      TEST_MODE: "full"
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DBNAME: ${MONGODB_DBNAME:-test}
    volumes:
      - ./test-results:/app/test-results
    command: ["npm", "run", "test:full"]
    depends_on:
      - base

  tests-rbt:
    image: rbt-playwright-suites
    environment:
      CI: "1"
      TEST_MODE: "rbt"
      RBT_N: ${RBT_N:-10}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DBNAME: ${MONGODB_DBNAME:-test}
    volumes:
      - ./test-results:/app/test-results
    command: ["sh", "-c", "npm run test:rbt"]
    depends_on:
      - base

  risk-update:
    image: rbt-playwright-suites
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DBNAME: ${MONGODB_DBNAME:-test}
    volumes:
      - ./test-results:/app/test-results
      - ./risk:/app/risk
    command: ["npm", "run", "risk:update"]
    depends_on:
      - base
